// ============================================================
// measures.dax
// All DAX measures for Sales Dashboard Semantic Model
// Import these into your Power BI Semantic Model
// ============================================================


// ── BASIC SALES MEASURES ─────────────────────────────────────

[Total Gross Sales] =
SUM(fact_sales[gross_sales])

[Total Net Sales] =
SUM(fact_sales[net_sales])

[Total Units Sold] =
SUM(fact_sales[quantity])

[Total Orders] =
DISTINCTCOUNT(fact_sales[order_id])

[Total Discounts] =
SUM(fact_sales[discount_amt])

[Total COGS] =
SUM(fact_sales[cogs])

[Gross Profit] =
SUM(fact_sales[profit])


// ── MARGIN MEASURES ──────────────────────────────────────────

[Profit Margin %] =
DIVIDE([Gross Profit], [Total Net Sales], 0) * 100

[Discount Rate %] =
DIVIDE([Total Discounts], [Total Gross Sales], 0) * 100

[Avg Order Value] =
DIVIDE([Total Net Sales], [Total Orders], 0)

[Avg Units per Order] =
DIVIDE([Total Units Sold], [Total Orders], 0)


// ── TIME INTELLIGENCE ────────────────────────────────────────

[Net Sales MTD] =
TOTALMTD([Total Net Sales], dim_date[date])

[Net Sales QTD] =
TOTALQTD([Total Net Sales], dim_date[date])

[Net Sales YTD] =
TOTALYTD([Total Net Sales], dim_date[date])

[Net Sales PY] =
CALCULATE([Total Net Sales], SAMEPERIODLASTYEAR(dim_date[date]))

[Net Sales PM] =
CALCULATE([Total Net Sales], DATEADD(dim_date[date], -1, MONTH))

[YoY Growth] =
DIVIDE([Total Net Sales] - [Net Sales PY], [Net Sales PY], 0)

[YoY Growth %] =
[YoY Growth] * 100

[MoM Growth] =
DIVIDE([Total Net Sales] - [Net Sales PM], [Net Sales PM], 0)

[MoM Growth %] =
[MoM Growth] * 100

[3M Rolling Sales] =
CALCULATE([Total Net Sales], DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -3, MONTH))


// ── RANKING ──────────────────────────────────────────────────

[Product Sales Rank] =
RANKX(
    ALL(dim_product[product_name]),
    [Total Net Sales],
    ,
    DESC,
    DENSE
)

[Customer Sales Rank] =
RANKX(
    ALL(dim_customer[customer_name]),
    [Total Net Sales],
    ,
    DESC,
    DENSE
)

[Top 10 Products Flag] =
IF([Product Sales Rank] <= 10, "Top 10", "Others")

[Top 10 Customers Flag] =
IF([Customer Sales Rank] <= 10, "Top 10", "Others")


// ── TARGETS & VARIANCES ──────────────────────────────────────
// Assumes a Sales_Targets table with [target_sales] column

[Sales Target] =
SUM(Sales_Targets[target_sales])

[Sales vs Target] =
[Total Net Sales] - [Sales Target]

[Sales vs Target %] =
DIVIDE([Sales vs Target], [Sales Target], 0) * 100

[Sales Attainment %] =
DIVIDE([Total Net Sales], [Sales Target], 0) * 100


// ── CUSTOMER METRICS ─────────────────────────────────────────

[Unique Customers] =
DISTINCTCOUNT(fact_sales[customer_key])

[Revenue per Customer] =
DIVIDE([Total Net Sales], [Unique Customers], 0)

[New Customers] =
CALCULATE(
    DISTINCTCOUNT(fact_sales[customer_key]),
    FILTER(
        dim_customer,
        CALCULATE(MIN(fact_sales[date_key])) >= MIN(dim_date[date_key])
    )
)


// ── DYNAMIC FORMATTING ───────────────────────────────────────

[Net Sales Formatted] =
VAR v = [Total Net Sales]
RETURN
    IF(v >= 1000000,
        FORMAT(v / 1000000, "#,##0.0") & "M",
        IF(v >= 1000,
            FORMAT(v / 1000, "#,##0.0") & "K",
            FORMAT(v, "#,##0")
        )
    )
